modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "spatialaudiosystem"
version = "1.0.4"
displayName = "Spatial Audio System"
logoFile = "icon.png"
authors = "hololocheck"
description = '''
A mod that lets you play custom MP3 and OGG audio files in-game.
Includes playback devices, recording devices, recording media, and range specification boards.
'''


[[dependencies.spatialaudiosystem]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spatialaudiosystem]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"
